### ISSUE TITLE
Representations cause excessive SQL queries

### ISSUE THREAD

**Issue by afrasier** [18F/State-TalentMAP-API#103]
Objects with a string representation included in their serialization are causing a high number of SQL calls

**Comment by afrasier** [comment]
@jseppi @burgwyn After investigating, this is being caused by our use of a list serializer for the nested list of language qualifications on positions - it's not slowing the database down very much; but the only proper solution is to either (1) render the list as only the qualification IDs, which adds more work for the front end to stitch that data together and/or (2) split it into it's own sub-route, like `/api/v1/position/{id}/language_qualifications/` but that also becomes cumbersome. I'd recommend just leaving it how it is, and maybe trimming down the nested serialized fields on the qualifications to just what front end needs/is using.

**Comment by afrasier** [comment]
Moving this to review/qa pending response, but there's no code to be written for this this sprint

**Comment by burgwyn** [comment]
I'm voting to delay and eventually go with option 1.
