### ISSUE TITLE
Consider inverting the specifying of read-only model fields

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP-API#107]
Ref https://github.com/18F/State-TalentMAP-API/commit/ab8a7b47b4fcebec08ea4fb9cf8d10c090f1e5d5#commitcomment-24093849

Rather than specifying the read-only fields of each model, consider specifying the fields that are modifiable instead.

**Comment by afrasier** [comment]
That'd probably be best, I'll have to poke around with DRF serializer meta objects since I know it has `read_only_fields` but I'm not sure if the inverse exists

**Comment by afrasier** [comment]
Maybe something like
```
class Meta:
    read_only_fields = "__all__"
    fields = ("writable_field_1",)
```
_might_ work, but I'll leave this for next sprint

**Comment by afrasier** [comment]
Ok, I have a PR ready for this once #127 is merged in I can rebase my local branch and push and PR. Surprisingly simple solution to this one.
