### ISSUE TITLE
Squash Migrations

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP-API#144]
Take existing migrations - through sprint 7 - and squash into a more compact state.

Looking for feedback from @afrasier & @jseppi

**Comment by jseppi** [comment]
That sounds fine to me -- I see no reason to keep them around.

**Comment by afrasier** [comment]
Yep, always good to squash periodically.

**Comment by burgwyn** [comment]
I vote for Sprint 10

**Comment by afrasier** [comment]
`squashmigrations` is giving a ton of circular dependencies, so it may be best to do the clean cut version of squashing which will require databases to be reset.
