### ISSUE TITLE
New filters and properties to support CDO Bidder Portfolio

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP-API#237]
In order to support the new CDO Bidder Portfolio page on the front-end, the following filters are required:

* For the `/client` endpoint, return the number of bids the user has in the "draft" and "submitted" state
    * ex: `{ id: 1, …, bid_information: { submitted: 2, draft: 4 }, … }`

* Ability to filter the `/client` endpoint by:
    * Clients bidding
    * Clients in Panel
    * Clients in Post

* For the `/client` endpoint, the ability to perform full text search on the CDO’s clients
    * Search by name and skill code

**Comment by afrasier** [comment]
Add `/api/v1/client/statistics/` to get client statistic counts
