### ISSUE TITLE
Handshake/No handshake filter on CDO clients

### ISSUE THREAD

**Issue by afrasier** [18F/State-TalentMAP-API#241]

**Comment by mjoyce91** [comment]
@afraiser - what's the new param associated with this?

**Comment by afrasier** [comment]
`/api/v1/clients/?bid_statistics__handshake_offered__gt=0` or `/api/v1/clients/?bid_statistics__handshake_offered=0`

You can also use handshake_accepted here, I left it this way so it's flexible
