### ISSUE TITLE
`UserProfileView not compatible with schema generation` logged

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP-API#271]
I noticed the following warning after starting up the API via `docker-compose up` and the initial load of the local swagger interface at localhost:8000:

```
app_1  | /usr/local/lib/python3.6/site-packages/django_filters/rest_framework/backends.py:93: UserWarning: <class 'talentmap_api.user_profile.views.profile.UserProfileView'> is not compatible with schema generation
app_1  |   "{} is not compatible with schema generation".format(view.__class__)
app_1  | /usr/local/lib/python3.6/site-packages/django_filters/rest_framework/backends.py:93: UserWarning: <class 'talentmap_api.bidding.views.bid.BidUpdateView'> is not compatible with schema generation
app_1  |   "{} is not compatible with schema generation".format(view.__class__)
```

Anything to worry about?

**Comment by afrasier** [comment]
It hasn't seemed to affected anything - I have noticed these errors but I can't seem to track down exactly what the cause is. I think it has something to do with the swagger view. I'll take a look when there's some free time, or if it starts causing errors.

**Comment by afrasier** [comment]
Turns out this is just the Swagger UI being finnicky, which will be disabled anyway in production.
