### ISSUE TITLE
Glossary - Cannot set `link` when creating a new glossary item

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP-API#340]
As seen during sprint review today.

**Comment by afrasier** [comment]
Yeah this doesn't occur locally, I think it might be a swagger/interactive doc issue. I'll look into it.

**Comment by afrasier** [comment]
Can't reproduce locally; this appears to be an issue with our AWS deployment (BAH CSN cloud rules). I don't think it will be an issue when deployed in DoS servers.

**Comment by jseppi** [comment]
Maybe have Nat check this out next time he's on-site and close it out if so?
