### ISSUE TITLE
Upgrade Django to 1.11.3

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP-API#35]
I just saw that there was a Django bugfix release a few days ago (7/1/17): https://docs.djangoproject.com/en/1.11/releases/1.11.3/

Might want to upgrade, though it looks like most of the fixes were for parts of the framework that this project won't be likely to use.

**Comment by afrasier** [comment]
Yeah most of this we aren't using, but it should be an easy enough upgrade so we should definitely roll it into next sprint so we stay as up-to-date as possible. Thanks for pointing it out! :)
