### ISSUE TITLE
Add ability to clone a search

### ISSUE THREAD

**Issue by afrasier** [18F/State-TalentMAP-API#54]

**Comment by mjoyce91** [comment]
@afrasier - is there an endpoint to clone, or is the expectation to just `POST` the same object to `api/v1/searches`? If there's logic built in to the naming convention of the cloned search, as described in https://github.com/18F/State-TalentMAP/issues/220, then I think we'd want to handle that on the server. But if the naming convention ends up not being a big deal, I think we can handle it on the client.

**Comment by afrasier** [comment]
I was just expecting to `POST` the same object. Maybe just append "(copy)" to the end, then they could edit it?

**Comment by mjoyce91** [comment]
I think one issue may be uniqueness. It's obviously not an issue from an API perspective, since the ID provides uniqueness - but from a usability perspective, it might be good to enforce unique names. I've opened an issue for further discussion: https://github.com/18F/State-TalentMAP/issues/668
